version: '2.4'
services:
  db:
    build: ./db
    image: mariadb
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
    - 3306:3306
    volumes:
    - ./db/initdb:/docker-entrypoint-initdb.d