version: '3.7'
services:
  db:
    container_name: db
    build: ./db
    image: mariadb
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
    - 3306:3306
    volumes:
    - ./db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql --user=root -e 'SELECT 1'
  authorization:
    container_name: authorization
    image: docker.io/br0z4rt/authorization
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db/authorization